#!/bin/sh
basedir=`dirname "$0"`

# cygpath -w means convert to native windows representation
case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

node --use-strict "$basedir/main.js" "$@"
ret=$?

exit $ret
